apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roi-dtc-m2022-u219/internal-image:v1.0.0
        env: 
        - name: PORT
          value: "8082"
        - name: GOOGLE_CLOUD_PROJECT
          value: "roi-dtc-m2022-u219"
        ports:
        - containerPort: 8082
            
        
